baseURL: "https://lanturnweekly.com/"
languageCode: "en-us"
title: "Lanturn Weekly"
paginate: 10

params:
  description: "Real news. Real actions. No noise."
  author: "Lanturn Weekly"
  tagline: "Light on, noise off."

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

outputs:
  home:
    - HTML
    - RSS

taxonomies:
  tag: tags

enableRobotsTXT: true

minify:
  disableXML: true
  minifyOutput: true
